#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#       not find it, but you have some other compatible shell such as ksh or
#       bash, then adjust the shebang line to use the alternative shell
#       For example, using ksh:
#
#           #!/bin/ksh
#
#       Busybox and similar reduced shells will NOT work, because this script
#       requires all of these POSIX shell features:
#         * functions;
#         * expansions "$var", "${var}", "${var:-default}", "${var+SET}",
#           "${var#prefix}", "${var%suffix}", and "$( cmd )";
#         * compound commands having a result command (like
#           if ... then ... else ... fi);
#         * various quoting mechanisms
#
#   Important for patching:
#
#   (3) This script is optional. You can just as easily run the build like:
#       $ gradle build
#
#   (4) IFS="" is parsed locally, so any changes to IFS become local
#
##############################################################################

# By default we should be in the correct project dir, but allow the user to
# override this by setting the GRADLE_USER_HOME variable.
if [ "${GRADLE_USER_HOME+x}" ] ; then
    GRADLE_HOME="${GRADLE_USER_HOME}/.gradle"
else
    GRADLE_HOME="$HOME/.gradle"
fi
export GRADLE_HOME

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD="maximum"

warn() {
    echo "$*" >&2
}

die() {
    echo
    echo "$*"
    echo
    exit 1
}

# OS specific support (must be 'true' or 'false').
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true   ;; #(
  NOTO* )           noto=true   ;; #(
  * )               false       ;;
esac

if [ "$cygwin" = true -o "$msys" = true ] ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --unix "$JAVACMD" )
fi

if [ ! -x "$JAVACMD" ] ; then
    die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH."
fi

if [ -z "$JAVA_HOME" ] ; then
    warn "WARNING: JAVA_HOME environment variable is not set."
fi

APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

APP_NAME="Gradle"
APP_BASE_NAME=$( basename "$0" )

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='" -Xmx64m" -Xms64m"'

# Use the maximum available, or set MAX_FD != -1 to use that value.
if ! (umask 077 && mkdir -p -- "$GRADLE_USER_HOME") 2>/dev/null; then
    # For MSYS / CYGWIN: move user's home profile into temp.
    [ -z "$GRADLE_USER_HOME" ] && GRADLE_USER_HOME="$( mktemp -d)"
    warn "Could not create files in $GRADLE_USER_HOME"
fi

if [ -z "$GRADLE_OPTS" ] ; then
    GRADLE_OPTS=$( echo "$DEFAULT_JVM_OPTS" | sed "s/^\"  *//" | sed 's/ *\"$//')
fi

if [ -z "$JAVA_OPTS" ] ; then
    JAVA_OPTS=$( echo "$DEFAULT_JVM_OPTS" | sed "s/^\"  *//" | sed 's/ *\"$//')
fi

GRADLE_APP_BASE_NAME=$( basename "$0" )
GRADLE_SCRIPT=$GRADLE_USER_HOME/gradle-script

# Disallow running with sudo, because it's dangerous and annoying.
if [ "$( id -u )" = 0 ] ; then
    die "ERROR: Do not run Gradle as root. If you're experiencing permission problems, you may need to fix the permissions of the Gradle installation."
fi

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
else
    JAVACMD="$( which java )"
fi

if [ ! -x "$JAVACMD" ] ; then
    die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.\
Please set the JAVA_HOME variable in your environment to match the\
location of your Java installation."
fi

if [ -z "$JAVA_HOME" ] ; then
    warn "WARNING: JAVA_HOME environment variable is not set."
fi

LANG=C
export LANG

# Increase the maximum file descriptors if we can.
if ! is_cygwin && ! is_mingw && ! is_noto ; then
    MAX_FD=$( ulimit -H -n ) ||
    warn "Could not query maximum file descriptor limit"
    case $MAX_FD in #(
      ''|soft) :;; #(
      *) ulimit -n $MAX_FD ||
        warn "Could not set maximum file descriptor limit to $MAX_FD"
    esac
fi

# Collect all arguments for the java command, and put them in an array to allow
# for word splitting if needed.
set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

# Stop when "xargs" by itself has handled all of its input in order to avoid
# the possibility of the shell bailing out while processing a note whose entry
# with -z would cause an IFS read bound which couldn't be satisfied.  the result
# of this if is always true.
eval "set -- $(printf '%s\n' "$@" | sed 's/^[^.]*/"$0"/; s/$/"/; $ !s/$/\n/') 2/dev/null" || true
exec "$JAVACMD" "$@"
